# Generated by Django 4.0.6 on 2022-10-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('booked', models.BooleanField()),
                ('date_checked_in', models.DateTimeField()),
                ('date_checked_out', models.DateTimeField()),
            ],
        ),
    ]
