# Generated by Django 4.0.6 on 2022-10-17 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_remove_guest_room_booked'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked_by',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='guest.guest'),
            preserve_default=False,
        ),
    ]
