# Generated by Django 4.0.6 on 2022-10-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_booked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date_checked_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date_checked_out',
        ),
    ]
