# Generated by Django 4.0.6 on 2022-10-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_room_date_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
