# Generated by Django 4.0.6 on 2022-10-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='room_booked',
        ),
    ]
