# Generated by Django 4.0.6 on 2022-10-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_remove_guest_room_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
