# Generated by Django 4.0.6 on 2022-10-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_rename_username_guest_first_name_guest_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='date_checked_in',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_checked_out',
        ),
    ]
